# Generated by Django 5.2 on 2025-08-29 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledpost',
            name='user_timezone',
            field=models.CharField(default='UTC', help_text="User's timezone for interpreting cron schedule", max_length=50),
        ),
    ]
