# Generated by Django 5.2 on 2025-08-29 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_scheduledpost_user_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledpost',
            name='cron_schedule',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
