# Generated by Django 5.2 on 2025-09-01 11:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0003_alter_scheduledpost_cron_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedpost',
            name='reddit_account',
            field=models.ForeignKey(help_text='The specific Reddit account used for this submission.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submission_history', to='reddit.redditaccount'),
        ),
        migrations.AddField(
            model_name='submittedpost',
            name='selftext',
            field=models.TextField(default='', help_text='Selftext at time of submission'),
        ),
        migrations.AddField(
            model_name='submittedpost',
            name='subreddit',
            field=models.CharField(default='', help_text='Subreddit at time of submission', max_length=100),
        ),
        migrations.AddField(
            model_name='submittedpost',
            name='title',
            field=models.CharField(default='', help_text='Title at time of submission', max_length=300),
        ),
        migrations.AlterField(
            model_name='submittedpost',
            name='scheduled_post',
            field=models.ForeignKey(blank=True, help_text='The scheduled post this submission came from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_posts', to='reddit.scheduledpost'),
        ),
    ]
