# Generated by Django 5.2 on 2025-09-01 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0004_submittedpost_reddit_account_submittedpost_selftext_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='submittedpost',
            name='reddit_username',
            field=models.CharField(default='', help_text='Reddit username at time of submission', max_length=100),
        ),
    ]
